name: 'Lighthouse Check'
description: 'GitHub Action for running @GoogleChromeLabs Lighthouse audits with bells and whistles 🔔'
inputs:
  urls:
    description: 'A comma-separated list of URLs to run Lighthouse Audits against.'
    required: true
steps:
- uses: actions/checkout@master
- run: npm install
runs:
  using: 'node12'
  main: 'index.js'
