name: 'Lighthouse Check'
description: 'GitHub Action for running @GoogleChromeLabs Lighthouse audits with bells and whistles 🔔'
branding:
  icon: 'activity'  
  color: 'green'
inputs:
  urls:
    description: 'A comma-separated list of URLs to run Lighthouse Audits against.'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
