name: Lighthouse Check

on: [push]

jobs:
  lighthouse-audit:
    runs-on: foosoftware/lighthouse-check:latest
    name: Lighthouse Check
    steps:
      - uses: actions/checkout@v1
      - name: Run Lighthouse
        id: lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: 'https://www.foo.software,https://www.foo.software/contact'
