name: Lighthouse Check

on: [push]

jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest
    name: Lighthouse Check
    steps:
      - name: Run Lighthouse
        id: lighthouse
        uses: actions/hello-world-docker-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
