name: Lighthouse Check

on: [push]

jobs:
  build:
    runs-on: foosoftware/lighthouse-check:latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Lighthouse
        run: |
          # lighthouse-check --urls https://www.foo.software
          echo "hi"
