name: Test Lighthouse Check
on: [pull_request]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: mkdir /tmp/artifacts
      - name: Run Lighthouse
        uses: ./
        id: lighthouseCheck
        with:
          urls: 'https://www.foo.software/nonexistent-tryagain'
      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: '95'
          minBestPracticesScore: '50'
          minPerformanceScore: '70'
          minProgressiveWebAppScore: '50'
          minSeoScore: '50'
