name: Test Lighthouse Check
on: [push]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: mkdir /tmp/artifacts
    - name: Run Lighthouse
      uses: ./
      with:
        author: ${{ github.actor }}
        awsAccessKeyId: ${{ secrets.LIGHTHOUSE_CHECK_AWS_ACCESS_KEY_ID }}
        awsBucket: ${{ secrets.LIGHTHOUSE_CHECK_AWS_BUCKET }}
        awsRegion: ${{ secrets.LIGHTHOUSE_CHECK_AWS_REGION }}
        awsSecretAccessKey: ${{ secrets.LIGHTHOUSE_CHECK_AWS_SECRET_ACCESS_KEY }}
        branch: ${{ github.ref }}
        minAccessibilityScore: 90
        minBestPracticesScore: 50
        minPerformanceScore: 50
        minProgressiveWebAppScore: 50
        minSeoScore: 50
        outputDirectory: /tmp/artifacts
        urls: 'https://www.foo.software,https://www.foo.software/contact'
        sha: ${{ github.sha }}
        slackWebhookUrl: ${{ secrets.LIGHTHOUSE_CHECK_WEBHOOK_URL }}
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/artifacts
