name: Test Lighthouse Check
on: [push]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - name: Run Lighthouse
      uses: ./
      with:
        urls: 'https://www.foo.software,https://www.foo.software/contact'
